export const products = `[{
    "ID":1,
    "color": "wite",
    "size": "s",
    "name": "ELLERY X M'O CAPSULE",
    "image": "images/pos1.jpg",
    "price": "52.00",
    "disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
       "quantity": 1
},{"ID":2,
"color": "black",
"size": "M","name": "ELLERY X M'O CAPSULE",
"image": "images/pos2.png",
"price": "52.00",
"disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",

"quantity": 1},{"ID":3,
"color": "yellow",
"size": "L", "name": "ELLERY X M'O CAPSULE",
"image": "images/pos3.png",
"price": "52.00",
"disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",

"quantity": 1},{"ID":4,
"color": "Green",
"size": "XL", "name": "ELLERY X M'O CAPSULE",
"image": "images/pos4.png",
"price": "52.00",
"disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",

"quantity": 1},{"ID":5,
"color":"Red",
"size": "XXL","name": "ELLERY X M'O CAPSULE",
"image": "images/pos5.png",
"price": "52.00",
"disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",

"quantity": 1},{"ID":6,
"color": "Blue",
"size": "C", "name": "ELLERY X M'O CAPSULE",
"image": "images/pos6.png",
"price": "52.00",
"disclaimer": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",

"quantity": 1}]`